### ISSUE TITLE
[BUG] Failed to Fetch

### ISSUE THREAD

**Issue by diggtrap** [YunzheZJU/holo-schedule#144] opened 2023-04-01 02:52 UTC
**Describe the bug**
Title

**To Reproduce**
Click the extension widget, see failed to load

**Expected behavior**
Should fetch the data

**Screenshots**
https://files.catbox.moe/l7he6r.png

**Desktop (please complete the following information):**
 - OS: Win10 Pro (64bit)
 - Browser: Chrome
 - Version: 111.0.5563.147

**Additional context**
Started happening today 31/03/23

**Comment by YunzheZJU** [comment] 2023-04-01 10:33
Sorry for the inconvenience. This is caused by a deploy issue of backend 'non-stop-story'. I'm trying to resolve it.

It is estimated that the service will be up in several hours.

I will close this issue then.

Thank you for your reporting!

**Comment by YunzheZJU** [comment] 2023-04-01 11:20
I am going to close this issue since HoloSchedule is back. Sorry for the inconvenience.

**Closed by YunzheZJU** 2023-04-01 11:20 UTC
Labels: bug
